package com.virtus.database.scripts;

public class ForeignKeysScripts {
    public static String createFKsIfNotExists(String schema) {

        ForeignKeyDefinition[] foreignKeys = new ForeignKeyDefinition[] {
                new ForeignKeyDefinition(
                        "destination_status_fkey",
                        "actions", "id_destination_status",
                        "status", "id_status"),
                new ForeignKeyDefinition(
                        "origin_status_fkey",
                        "actions", "id_origin_status",
                        "status", "id_status"),
                new ForeignKeyDefinition(
                        "actions_fkey",
                        "actions_status", "id_action",
                        "actions", "id_action"),
                new ForeignKeyDefinition(
                        "origin_actions_status_fkey",
                        "actions_status", "id_origin_status",
                        "status", "id_status"),
                new ForeignKeyDefinition(
                        "destination_actions_status_fkey",
                        "actions_status", "id_destination_status",
                        "status", "id_status"),
                new ForeignKeyDefinition("action_fkey", "activities", "id_action", "actions", "id_action"),
                new ForeignKeyDefinition("workflow_fkey", "activities", "id_workflow", "workflows", "id_workflow"),
                new ForeignKeyDefinition("activities_fkey", "activities_roles", "id_activity", "activities",
                        "id_activity"),
                new ForeignKeyDefinition("roles_fkey", "activities_roles", "id_role", "roles", "id_role"),
                new ForeignKeyDefinition("authors_ciclos_fkey", "ciclos", "id_author", "users", "id_user"),
                new ForeignKeyDefinition("status_ciclos_fkey", "ciclos", "id_status", "status", "id_status"),
                new ForeignKeyDefinition("entidades_ciclos_entidades_fkey", "ciclos_entidades", "id_entidade",
                        "entidades", "id_entidade"),
                new ForeignKeyDefinition("ciclos_ciclos_entidades_fkey", "ciclos_entidades", "id_ciclo", "ciclos",
                        "id_ciclo"),
                new ForeignKeyDefinition("authors_ciclos_entidades_fkey", "ciclos_entidades", "id_author", "users",
                        "id_user"),
                new ForeignKeyDefinition("status_ciclos_entidades_fkey", "ciclos_entidades", "id_status", "status",
                        "id_status"),
                new ForeignKeyDefinition("authors_componentes_fkey", "componentes", "id_author", "users", "id_user"),
                new ForeignKeyDefinition("status_componentes_fkey", "componentes", "id_status", "status", "id_status"),
                new ForeignKeyDefinition("componentes_componentes_pilares_fkey", "componentes_pilares", "id_componente",
                        "componentes", "id_componente"),
                new ForeignKeyDefinition("pilares_componentes_pilares_fkey", "componentes_pilares", "id_pilar",
                        "pilares", "id_pilar"),
                new ForeignKeyDefinition("authors_componentes_pilares_fkey", "componentes_pilares", "id_author",
                        "users", "id_user"),
                new ForeignKeyDefinition("status_componentes_pilares_fkey", "componentes_pilares", "id_status",
                        "status", "id_status"),
                new ForeignKeyDefinition("users_fkey", "elementos", "id_author", "users", "id_user"),
                new ForeignKeyDefinition("status_elementos_fkey", "elementos", "id_status", "status", "id_status"),
                new ForeignKeyDefinition("tipos_notas_fkey", "elementos_componentes", "id_tipo_nota", "tipos_notas",
                        "id_tipo_nota"),
                new ForeignKeyDefinition("elementos_elementos_componentes_fkey", "elementos_componentes", "id_elemento",
                        "elementos", "id_elemento"),
                new ForeignKeyDefinition("componentes_elementos_componentes_fkey", "elementos_componentes",
                        "id_componente", "componentes", "id_componente"),
                new ForeignKeyDefinition("authors_elementos_componentes_fkey", "elementos_componentes", "id_author",
                        "users", "id_user"),
                new ForeignKeyDefinition("status_elementos_componentes_fkey", "elementos_componentes", "id_status",
                        "status", "id_status"),
                new ForeignKeyDefinition("authors_entidades_fkey", "entidades", "id_author", "users", "id_user"),
                new ForeignKeyDefinition("status_entidades_fkey", "entidades", "id_status", "status", "id_status"),
                new ForeignKeyDefinition("authors_escritorios_fkey", "escritorios", "id_author", "users", "id_user"),
                new ForeignKeyDefinition("status_escritorios_fkey", "escritorios", "id_status", "status", "id_status"),
                new ForeignKeyDefinition("activities_features_activities_fkey", "features_activities", "id_activity",
                        "activities", "id_activity"),
                new ForeignKeyDefinition("features_features_activities_fkey", "features_activities", "id_feature",
                        "features", "id_feature"),
                new ForeignKeyDefinition("roles_features_roles_fkey", "features_roles", "id_role", "roles", "id_role"),
                new ForeignKeyDefinition("authors_pilares_fkey", "pilares", "id_author", "users", "id_user"),
                new ForeignKeyDefinition("status_pilares_fkey", "pilares", "id_status", "status", "id_status"),
                new ForeignKeyDefinition("pilares_pilares_ciclos_fkey", "pilares_ciclos", "id_pilar", "pilares",
                        "id_pilar"),
                new ForeignKeyDefinition("ciclos_pilares_ciclos_fkey", "pilares_ciclos", "id_ciclo", "ciclos",
                        "id_ciclo"),
                new ForeignKeyDefinition("authors_pilares_ciclos_fkey", "pilares_ciclos", "id_author", "users",
                        "id_user"),
                new ForeignKeyDefinition("status_pilares_ciclos_fkey", "pilares_ciclos", "id_status", "status",
                        "id_status"),
                new ForeignKeyDefinition("entidades_planos_fkey", "planos", "id_entidade", "entidades", "id_entidade"),
                new ForeignKeyDefinition("authors_planos_fkey", "planos", "id_author", "users", "id_user"),
                new ForeignKeyDefinition("status_planos_fkey", "planos", "id_status", "status", "id_status"),
                new ForeignKeyDefinition("entidades_produtos_ciclos_fkey", "produtos_ciclos", "id_entidade",
                        "entidades", "id_entidade"),
                new ForeignKeyDefinition("ciclos_produtos_ciclos_fkey", "produtos_ciclos", "id_ciclo", "ciclos",
                        "id_ciclo"),
                new ForeignKeyDefinition("authors_produtos_ciclos_fkey", "produtos_ciclos", "id_author", "users",
                        "id_user"),
                new ForeignKeyDefinition("status_produtos_ciclos_fkey", "produtos_ciclos", "id_status", "status",
                        "id_status"),
                new ForeignKeyDefinition("entidades_produtos_pilares_fkey", "produtos_pilares", "id_entidade",
                        "entidades", "id_entidade"),
                new ForeignKeyDefinition("ciclos_produtos_pilares_fkey", "produtos_pilares", "id_ciclo", "ciclos",
                        "id_ciclo"),
                new ForeignKeyDefinition("pilares_produtos_pilares_fkey", "produtos_pilares", "id_pilar", "pilares",
                        "id_pilar"),
                new ForeignKeyDefinition("authors_produtos_pilares_fkey", "produtos_pilares", "id_author", "users",
                        "id_user"),
                new ForeignKeyDefinition("status_produtos_pilares_fkey", "produtos_pilares", "id_status", "status",
                        "id_status"),
                new ForeignKeyDefinition("entidades_produtos_componentes_fkey", "produtos_componentes", "id_entidade",
                        "entidades", "id_entidade"),
                new ForeignKeyDefinition("ciclos_produtos_componentes_fkey", "produtos_componentes", "id_ciclo",
                        "ciclos", "id_ciclo"),
                new ForeignKeyDefinition("pilares_produtos_componentes_fkey", "produtos_componentes", "id_pilar",
                        "pilares", "id_pilar"),
                new ForeignKeyDefinition("componentes_produtos_componentes_fkey", "produtos_componentes",
                        "id_componente", "componentes", "id_componente"),
                new ForeignKeyDefinition("authors_produtos_componentes_fkey", "produtos_componentes", "id_author",
                        "users", "id_user"),
                new ForeignKeyDefinition("status_produtos_componentes_fkey", "produtos_componentes", "id_status",
                        "status", "id_status"),
                new ForeignKeyDefinition("features_features_roles_fkey", "features_roles", "id_feature", "features",
                        "id_feature"),
                new ForeignKeyDefinition("roles_features_roles_fkey", "features_roles", "id_role", "roles", "id_role"),
                new ForeignKeyDefinition("elementos_itens_fkey", "itens", "id_elemento", "elementos", "id_elemento"),
                new ForeignKeyDefinition("authors_pilares_fkey", "pilares", "id_author", "users", "id_user"),
                new ForeignKeyDefinition("status_pilares_fkey", "pilares", "id_status", "status", "id_status"),
                new ForeignKeyDefinition("pilares_pilares_ciclos_fkey", "pilares_ciclos", "id_pilar", "pilares",
                        "id_pilar"),
                new ForeignKeyDefinition("ciclos_pilares_ciclos_fkey", "pilares_ciclos", "id_ciclo", "ciclos",
                        "id_ciclo"),
                new ForeignKeyDefinition("authors_pilares_ciclos_fkey", "pilares_ciclos", "id_author", "users",
                        "id_user"),
                new ForeignKeyDefinition("status_pilares_ciclos_fkey", "pilares_ciclos", "id_status", "status",
                        "id_status"),
                new ForeignKeyDefinition("entidades_planos_fkey", "planos", "id_entidade", "entidades", "id_entidade"),
                new ForeignKeyDefinition("authors_planos_fkey", "planos", "id_author", "users", "id_user"),
                new ForeignKeyDefinition("status_planos_fkey", "planos", "id_status", "status", "id_status"),
                new ForeignKeyDefinition("entidades_produtos_ciclos_fkey", "produtos_ciclos", "id_entidade",
                        "entidades", "id_entidade"),
                new ForeignKeyDefinition("ciclos_produtos_ciclos_fkey", "produtos_ciclos", "id_ciclo", "ciclos",
                        "id_ciclo"),
                new ForeignKeyDefinition("authors_produtos_ciclos_fkey", "produtos_ciclos", "id_author", "users",
                        "id_user"),
                new ForeignKeyDefinition("status_produtos_ciclos_fkey", "produtos_ciclos", "id_status", "status",
                        "id_status"),
                new ForeignKeyDefinition("entidades_produtos_pilares_fkey", "produtos_pilares", "id_entidade",
                        "entidades", "id_entidade"),
                new ForeignKeyDefinition("ciclos_produtos_pilares_fkey", "produtos_pilares", "id_ciclo", "ciclos",
                        "id_ciclo"),
                new ForeignKeyDefinition("pilares_produtos_pilares_fkey", "produtos_pilares", "id_pilar", "pilares",
                        "id_pilar"),
                new ForeignKeyDefinition("authors_produtos_pilares_fkey", "produtos_pilares", "id_author", "users",
                        "id_user"),
                new ForeignKeyDefinition("status_produtos_pilares_fkey", "produtos_pilares", "id_status", "status",
                        "id_status"),
                new ForeignKeyDefinition("entidades_produtos_componentes_fkey", "produtos_componentes", "id_entidade",
                        "entidades", "id_entidade"),
                new ForeignKeyDefinition("ciclos_produtos_componentes_fkey", "produtos_componentes", "id_ciclo",
                        "ciclos", "id_ciclo"),
                new ForeignKeyDefinition("pilares_produtos_componentes_fkey", "produtos_componentes", "id_pilar",
                        "pilares", "id_pilar"),
                new ForeignKeyDefinition("componentes_produtos_componentes_fkey", "produtos_componentes",
                        "id_componente", "componentes", "id_componente"),
                new ForeignKeyDefinition("authors_produtos_componentes_fkey", "produtos_componentes", "id_author",
                        "users", "id_user"),
                new ForeignKeyDefinition("status_produtos_componentes_fkey", "produtos_componentes", "id_status",
                        "status", "id_status"),
                new ForeignKeyDefinition("entidades_produtos_tipos_notas_fkey", "produtos_tipos_notas", "id_entidade",
                        "entidades", "id_entidade"),
                new ForeignKeyDefinition("ciclos_produtos_tipos_notas_fkey", "produtos_tipos_notas", "id_ciclo",
                        "ciclos", "id_ciclo"),
                new ForeignKeyDefinition("pilares_produtos_tipos_notas_fkey", "produtos_tipos_notas", "id_pilar",
                        "pilares", "id_pilar"),
                new ForeignKeyDefinition("componentes_produtos_tipos_notas_fkey", "produtos_tipos_notas",
                        "id_componente", "componentes", "id_componente"),
                new ForeignKeyDefinition("tipos_notas_produtos_tipos_notas_fkey", "produtos_tipos_notas",
                        "id_tipo_nota", "tipos_notas", "id_tipo_nota"),
                new ForeignKeyDefinition("authors_produtos_tipos_notas_fkey", "produtos_tipos_notas", "id_author",
                        "users", "id_user"),
                new ForeignKeyDefinition("status_produtos_tipos_notas_fkey", "produtos_tipos_notas", "id_status",
                        "status", "id_status"),
                new ForeignKeyDefinition("entidades_produtos_elementos_fkey", "produtos_elementos", "id_entidade",
                        "entidades", "id_entidade"),
                new ForeignKeyDefinition("ciclos_produtos_elementos_fkey", "produtos_elementos", "id_ciclo", "ciclos",
                        "id_ciclo"),
                new ForeignKeyDefinition("pilares_produtos_elementos_fkey", "produtos_elementos", "id_pilar", "pilares",
                        "id_pilar"),
                new ForeignKeyDefinition("componentes_produtos_elementos_fkey", "produtos_elementos", "id_componente",
                        "componentes", "id_componente"),
                new ForeignKeyDefinition("tipos_notas_produtos_elementos_fkey", "produtos_elementos", "id_tipo_nota",
                        "tipos_notas", "id_tipo_nota"),
                new ForeignKeyDefinition("elementos_produtos_elementos_fkey", "produtos_elementos", "id_elemento",
                        "elementos", "id_elemento"),
                new ForeignKeyDefinition("authors_produtos_elementos_fkey", "produtos_elementos", "id_author", "users",
                        "id_user"),
                new ForeignKeyDefinition("status_produtos_elementos_fkey", "produtos_elementos", "id_status", "status",
                        "id_status"),
                new ForeignKeyDefinition("entidades_produtos_itens_fkey", "produtos_itens", "id_entidade", "entidades",
                        "id_entidade"),
                new ForeignKeyDefinition("ciclos_produtos_itens_fkey", "produtos_itens", "id_ciclo", "ciclos",
                        "id_ciclo"),
                new ForeignKeyDefinition("pilares_produtos_itens_fkey", "produtos_itens", "id_pilar", "pilares",
                        "id_pilar"),
                new ForeignKeyDefinition("componentes_produtos_itens_fkey", "produtos_itens", "id_componente",
                        "componentes", "id_componente"),
                new ForeignKeyDefinition("elementos_produtos_itens_fkey", "produtos_itens", "id_elemento", "elementos",
                        "id_elemento"),
                new ForeignKeyDefinition("itens_produtos_itens_fkey", "produtos_itens", "id_item", "itens", "id_item"),
                new ForeignKeyDefinition("authors_produtos_itens_fkey", "produtos_itens", "id_author", "users",
                        "id_user"),
                new ForeignKeyDefinition("status_produtos_itens_fkey", "produtos_itens", "id_status", "status",
                        "id_status"),
                new ForeignKeyDefinition("authors_tipos_notas_fkey", "tipos_notas", "id_author", "users", "id_user"),
                new ForeignKeyDefinition("tipos_notas_tipos_notas_componentes_fkey", "tipos_notas_componentes",
                        "id_tipo_nota", "tipos_notas", "id_tipo_nota"),
                new ForeignKeyDefinition("componentes_tipos_notas_componentes_fkey", "tipos_notas_componentes",
                        "id_componente", "componentes", "id_componente"),
                new ForeignKeyDefinition("status_tipos_notas_fkey", "tipos_notas", "id_status", "status", "id_status"),
                new ForeignKeyDefinition("roles_users_fkey", "users", "id_role", "roles", "id_role"),
                new ForeignKeyDefinition("authors_users_fkey", "users", "id_author", "users", "id_user"),
                new ForeignKeyDefinition("status_users_fkey", "users", "id_status", "status", "id_status"),
                new ForeignKeyDefinition("entidades_jurisdicoes_fkey", "jurisdicoes", "id_entidade", "entidades",
                        "id_entidade"),
                new ForeignKeyDefinition("escritorios_jurisdicoes_fkey", "jurisdicoes", "id_escritorio", "escritorios",
                        "id_escritorio"),
                new ForeignKeyDefinition("authors_jurisdicoes_fkey", "jurisdicoes", "id_author", "users", "id_user"),
                new ForeignKeyDefinition("status_jurisdicoes_fkey", "jurisdicoes", "id_status", "status", "id_status"),
                new ForeignKeyDefinition("usuarios_membros_fkey", "membros", "id_usuario", "users", "id_user"),
                new ForeignKeyDefinition("escritorios_membros_fkey", "membros", "id_escritorio", "escritorios",
                        "id_escritorio"),
                new ForeignKeyDefinition("authors_membros_fkey", "membros", "id_author", "users", "id_user"),
                new ForeignKeyDefinition("status_membros_fkey", "membros", "id_status", "status", "id_status") };

        StringBuilder sqlBuilder = new StringBuilder();

        for (ForeignKeyDefinition fk : foreignKeys) {
            sqlBuilder.append("IF NOT EXISTS (")
                    .append("SELECT 1 FROM sys.objects WHERE name = '").append(fk.name)
                    .append("' AND type IN (N'F')) BEGIN ")
                    .append("ALTER TABLE ").append(schema).append(".").append(fk.sourceTable)
                    .append(" ADD CONSTRAINT ").append(fk.name)
                    .append(" FOREIGN KEY (").append(fk.sourceColumn).append(")")
                    .append(" REFERENCES ").append(schema).append(".").append(fk.destinationTable)
                    .append(" (").append(fk.destinationColumn).append(")")
                    .append(" ON DELETE NO ACTION ON UPDATE NO ACTION END;\n");
        }

        return sqlBuilder.toString();
    }
}

class ForeignKeyDefinition {
    String name;
    String sourceTable;
    String sourceColumn;
    String destinationTable;
    String destinationColumn;

    public ForeignKeyDefinition(String name, String sourceTable, String sourceColumn,
            String destinationTable, String destinationColumn) {
        this.name = name;
        this.sourceTable = sourceTable;
        this.sourceColumn = sourceColumn;
        this.destinationTable = destinationTable;
        this.destinationColumn = destinationColumn;
    }
}