package com.virtus.database.scripts;

public class JurisdictionsScripts {

    static class Jurisdicao {
        String siglaEntidade;
        String abreviaturaEscritorio;

        public Jurisdicao(String siglaEntidade, String abreviaturaEscritorio) {
            this.siglaEntidade = siglaEntidade;
            this.abreviaturaEscritorio = abreviaturaEscritorio;
        }
    }

        public static String insertJurisdictionIfNotExists(String schema) {
            // Array com todas as jurisdições
            Jurisdicao[] jurisdicoes = {
                new Jurisdicao("ABBOTTPREV", "ERSP"),
                new Jurisdicao("ABBPREV", "ERSP"),
                new Jurisdicao("ACEPREV", "ERMG"),
                new Jurisdicao("ACIPREV", "ERSP"),
                new Jurisdicao("ACOS", "ERMG"),
                new Jurisdicao("AEROS", "ERSP"),
                new Jurisdicao("AERUS", "ERRJ"),
                new Jurisdicao("AGPREV", "ERMG"),
                new Jurisdicao("AGROS", "ERMG"),
                new Jurisdicao("AKZOPREV", "ERSP"),
                new Jurisdicao("ALBAPREV", "ERMG"),
                new Jurisdicao("ALCANPREV", "ERSP"),
                new Jurisdicao("ALCOA PREVI", "ERSP"),
                new Jurisdicao("ALEPEPREV", "ERPE"),
                new Jurisdicao("ALLERGAN PREV", "ERSP"),
                new Jurisdicao("ALPAPREV", "ERSP"),
                new Jurisdicao("ALPHA", "ERRS"),
                new Jurisdicao("ALPREV", "ERPE"),
                new Jurisdicao("ALSTOM", "ERSP"),
                new Jurisdicao("ANABBPREV", "ERDF"),
                new Jurisdicao("APCDPREV", "ERSP"),
                new Jurisdicao("APREV", "ERSP"),
                new Jurisdicao("ARM PREV", "ERSP"),
                new Jurisdicao("ARUS", "ERMG"),
                new Jurisdicao("ATLANTIC", "ERRJ"),
                new Jurisdicao("ATTILIO FONTANA", "ERSP"),
                new Jurisdicao("AUTOLATINA", "ERSP"),
                new Jurisdicao("AVELINO", "ERRS"),
                new Jurisdicao("AVONPREV", "ERSP"),
                new Jurisdicao("AZENPREV", "ERSP"),
                new Jurisdicao("B - D PREV", "ERSP"),
                new Jurisdicao("BANDEPREV", "ERPE"),
                new Jurisdicao("BANESES", "ERMG"),
                new Jurisdicao("BANESPREV", "ERSP"),
                new Jurisdicao("BANORTE", "ERPE"),
                new Jurisdicao("BANRISUL/FBSS", "ERRS"),
                new Jurisdicao("BASES", "ERMG"),
                new Jurisdicao("BASF PC", "ERSP"),
                new Jurisdicao("BAYERPREV", "ERSP"),
                new Jurisdicao("BB PREVIDENCIA", "ERDF"),
                new Jurisdicao("BCO. SUMITOMO", "ERSP"),
                new Jurisdicao("BCPREV", "ERSP"),
                new Jurisdicao("BELAUTO", "ERRJ"),
                new Jurisdicao("BERONPREV", "ERPE"),
                new Jurisdicao("BETZDEARBORN", "ERSP"),
                new Jurisdicao("BIEMPRESARIAL", "ERSP"),
                new Jurisdicao("BIPREV", "ERSP"),
                new Jurisdicao("BLS PREV", "ERSP"),
                new Jurisdicao("BOAVISTAPREV", "ERSP"),
                new Jurisdicao("BOMPREV", "ERPE"),
                new Jurisdicao("BOSCHPREV", "ERSP"),
                new Jurisdicao("BOSTONPREV", "ERSP"),
                new Jurisdicao("BOTICARIO PREV", "ERRS"),
                new Jurisdicao("BP PREV", "ERRJ"),
                new Jurisdicao("BRASILETROS", "ERRJ"),
                new Jurisdicao("BRASLIGHT", "ERRJ"),
                new Jurisdicao("BRASPREV", "ERRJ"),
                new Jurisdicao("BRF PREVIDÊNCIA", "ERSP"),
                new Jurisdicao("BRISTOL-MYERS", "ERSP"),
                new Jurisdicao("BUNGEPREV", "ERSP"),
                new Jurisdicao("CABEA", "ERMG"),
                new Jurisdicao("CABEC", "ERPE"),
                new Jurisdicao("CAEMI", "ERRJ"),
                new Jurisdicao("CAFBEP", "ERMG"),
                new Jurisdicao("CAGEPREV", "ERPE"),
                new Jurisdicao("CANADA LIFE", "ERRJ"),
                new Jurisdicao("CAPAF", "ERMG"),
                new Jurisdicao("CAPEB", "ERPE"),
                new Jurisdicao("CAPEF", "ERPE"),
                new Jurisdicao("CAPESESP", "ERRJ"),
                new Jurisdicao("CAPOF", "ERPE"),
                new Jurisdicao("CARBOPREV", "ERSP"),
                new Jurisdicao("CARFEPE", "ERMG"),
                new Jurisdicao("CARGILLPREV", "ERSP"),
                new Jurisdicao("CARREFOURPREV", "ERSP"),
                new Jurisdicao("CARTAPREV", "ERDF"),
                new Jurisdicao("CASANPREV", "ERRS"),
                new Jurisdicao("CASFAM", "ERMG"),
                new Jurisdicao("CAVA", "ERMG"),
                new Jurisdicao("CBS", "ERSP"),
                new Jurisdicao("CELOS", "ERRS"),
                new Jurisdicao("CELPOS", "ERPE"),
                new Jurisdicao("CENTRUS", "ERDF"),
                new Jurisdicao("CENTRUS/MT", "ERMG"),
                new Jurisdicao("CEPLUS", "ERMG"),
                new Jurisdicao("CE-PREVCOM", "ERPE"),
                new Jurisdicao("CERES", "ERDF"),
                new Jurisdicao("CIASPREV", "ERSP"),
                new Jurisdicao("CIBRIUS", "ERDF"),
                new Jurisdicao("CIC-PREV", "ERRS"),
                new Jurisdicao("CIFRAO", "ERRJ"),
                new Jurisdicao("CISPER PP", "ERSP"),
                new Jurisdicao("CITIPREVI", "ERSP"),
                new Jurisdicao("COHAPREV", "ERRS"),
                new Jurisdicao("COMPESAPREV", "ERPE"),
                new Jurisdicao("COMSHELL", "ERRJ"),
                new Jurisdicao("CORRENTE", "ERSP"),
                new Jurisdicao("CP PREV", "ERSP"),
                new Jurisdicao("CREDIPREV", "ERMG"),
                new Jurisdicao("CREMERPREV", "ERRS"),
                new Jurisdicao("CRYOVAC", "ERSP"),
                new Jurisdicao("CURITIBAPREV", "ERRS"),
                new Jurisdicao("CYAMPREV", "ERSP"),
                new Jurisdicao("DANAPREV", "ERRS"),
                new Jurisdicao("DAREXPREV", "ERSP"),
                new Jurisdicao("DATUSPREV", "ERRS"),
                new Jurisdicao("DCPREV", "ERSP"),
                new Jurisdicao("DERMINAS", "ERMG"),
                new Jurisdicao("DESBAN", "ERMG"),
                new Jurisdicao("DF-PREVICOM", "ERDF"),
                new Jurisdicao("DIVERPREV", "ERSP"),
                new Jurisdicao("DURATEX", "ERSP"),
                new Jurisdicao("EATONPREV", "ERSP"),
                new Jurisdicao("ECONOMUS", "ERSP"),
                new Jurisdicao("ECOS", "ERMG"),
                new Jurisdicao("EDS PREV", "ERSP"),
                new Jurisdicao("ELANCO PREV", "ERSP"),
                new Jurisdicao("ELBA", "ERMG"),
                new Jurisdicao("ELETRA", "ERMG"),
                new Jurisdicao("ELETROS", "ERRJ"),
                new Jurisdicao("ELOS", "ERRS"),
                new Jurisdicao("EMBRAER PREV", "ERSP"),
                new Jurisdicao("ENERGISAPREV", "ERSP"),
                new Jurisdicao("ENERPREV", "ERSP"),
                new Jurisdicao("ENERSUL", "ERMG"),
                new Jurisdicao("EQTPREV", "ERPE"),
                new Jurisdicao("ESCELSOS", "ERMG"),
                new Jurisdicao("F.GUIMARAES", "ERRJ"),
                new Jurisdicao("FABASA", "ERMG"),
                new Jurisdicao("FABRI", "ERRJ"),
                new Jurisdicao("FACEAL", "ERPE"),
                new Jurisdicao("FACEB", "ERDF"),
                new Jurisdicao("FACEPI", "ERPE"),
                new Jurisdicao("FACHESF", "ERPE"),
                new Jurisdicao("FACOPAC", "ERSP"),
                new Jurisdicao("FAECES", "ERMG"),
                new Jurisdicao("FAELBA", "ERMG"),
                new Jurisdicao("FAELCE", "ERPE"),
                new Jurisdicao("FAIRPLAN", "ERSP"),
                new Jurisdicao("FAMILIA PREVIDENCIA", "ERRS"),
                new Jurisdicao("FAPA", "ERRS"),
                new Jurisdicao("FAPECE", "ERPE"),
                new Jurisdicao("FAPERS", "ERRS"),
                new Jurisdicao("FAPES", "ERRJ"),
                new Jurisdicao("FAPIEB", "ERRS"),
                new Jurisdicao("FASASS", "ERSP"),
                new Jurisdicao("FASBEMGE", "ERMG"),
                new Jurisdicao("FASC", "ERSP"),
                new Jurisdicao("FASERN", "ERPE"),
                new Jurisdicao("FATL", "ERRJ"),
                new Jurisdicao("FBEMGEPREV", "ERMG"),
                new Jurisdicao("FBRTPREV", "ERDF"),
                new Jurisdicao("FEMCO", "ERSP"),
                new Jurisdicao("FENIPREV", "ERSP"),
                new Jurisdicao("FFMB", "ERRS"),
                new Jurisdicao("FGV-PREVI", "ERRJ"),
                new Jurisdicao("FIBERGLAS", "ERSP"),
                new Jurisdicao("FIBRA", "ERRS"),
                new Jurisdicao("FIOPREV", "ERRJ"),
                new Jurisdicao("FIPECQ", "ERDF"),
                new Jurisdicao("FMCPREV", "ERRJ"),
                new Jurisdicao("FOLHAPREV", "ERSP"),
                new Jurisdicao("FORD", "ERSP"),
                new Jurisdicao("FORLUZ", "ERMG"),
                new Jurisdicao("FPMN", "ERSP"),
                new Jurisdicao("FRANCISCO CONDE", "ERSP"),
                new Jurisdicao("FRANPREV", "ERSP"),
                new Jurisdicao("FUCAE", "ERRS"),
                new Jurisdicao("FUCAP", "ERRJ"),
                new Jurisdicao("FUMAC", "ERSP"),
                new Jurisdicao("FUMPRESC", "ERRS"),
                new Jurisdicao("FUNASA", "ERPE"),
                new Jurisdicao("FUNBEP", "ERRS"),
                new Jurisdicao("FUNCASAL", "ERPE"),
                new Jurisdicao("FUNCEF", "ERSP"),
                new Jurisdicao("VIVEST", "ERSP"),
                new Jurisdicao("FUND. BRASILSAT", "ERRS"),
                new Jurisdicao("FUNDAÇÃO 14 PP", "ERRJ"),
                new Jurisdicao("FUNDACAO COPEL", "ERRS"),
                new Jurisdicao("FUNDACAO CORSAN", "ERRS"),
                new Jurisdicao("FUNDAÇÃO LIBERTAS", "ERMG"),
                new Jurisdicao("FUNDAMBRAS", "ERMG"),
                new Jurisdicao("FUNDIAGUA", "ERDF"),
                new Jurisdicao("FUNDO PARANA", "ERRS"),
                new Jurisdicao("FUNEPP", "ERSP"),
                new Jurisdicao("FUNGRAPA", "ERMG"),
                new Jurisdicao("FUNPADEPAR", "ERRS"),
                new Jurisdicao("FUNPRESP-EXE", "ERDF"),
                new Jurisdicao("FUNPRESP-JUD", "ERDF"),
                new Jurisdicao("FUNREDE", "ERSP"),
                new Jurisdicao("FUNSEJEM", "ERSP"),
                new Jurisdicao("FUNSSEST", "ERMG"),
                new Jurisdicao("FUNTERRA", "ERDF"),
                new Jurisdicao("FUSAN", "ERRS"),
                new Jurisdicao("FUSESC", "ERRS"),
                new Jurisdicao("FUTURA II", "ERSP"),
                new Jurisdicao("FUTURA PREV", "ERSP"),
                new Jurisdicao("GAROTO", "ERMG"),
                new Jurisdicao("GASIUS", "ERRJ"),
                new Jurisdicao("GEAP AUTOGESTÃO EM SAÚDE", "ERDF"),
                new Jurisdicao("GEBSA-PREV", "ERSP"),
                new Jurisdicao("GEIPREV", "ERDF"),
                new Jurisdicao("GERDAU", "ERRS"),
                new Jurisdicao("GOODYEAR", "ERSP"),
                new Jurisdicao("GTMPREVI", "ERPE"),
                new Jurisdicao("GZM PREVI", "ERSP"),
                new Jurisdicao("HERINGPREV", "ERRS"),
                new Jurisdicao("IAJA", "ERDF"),
                new Jurisdicao("IBM", "ERRJ"),
                new Jurisdicao("IBP", "ERSP"),
                new Jurisdicao("ICATUFMP", "ERRJ"),
                new Jurisdicao("ICI CORAL", "ERSP"),
                new Jurisdicao("IFM", "ERSP"),
                new Jurisdicao("IJMS", "ERSP"),
                new Jurisdicao("INDUSPREVI", "ERRS"),
                new Jurisdicao("INDUSPREVI-SUL", "ERRS"),
                new Jurisdicao("INERGUS", "ERPE"),
                new Jurisdicao("INFRAPREV", "ERRJ"),
                new Jurisdicao("INOVAR PREVIDENCIA", "ERSP"),
                new Jurisdicao("INSTITUTO AMBEV", "ERSP"),
                new Jurisdicao("ISBRE", "ERRS"),
                new Jurisdicao("ISSS/SANDOZ", "ERSP"),
                new Jurisdicao("ITAU UNIBANCO", "ERSP"),
                new Jurisdicao("ITAUBANK", "ERSP"),
                new Jurisdicao("ITAUSAINDL", "ERSP"),
                new Jurisdicao("J & HIGGINS", "ERSP"),
                new Jurisdicao("JOHNSON", "ERSP"),
                new Jurisdicao("JOSAPREV", "ERRS"),
                new Jurisdicao("JUSPREV", "ERRS"),
                new Jurisdicao("KPMG PREV", "ERSP"),
                new Jurisdicao("KRAFT PREV", "ERRS"),
                new Jurisdicao("LANXESSPREV", "ERSP"),
                new Jurisdicao("LILLYPREV", "ERSP"),
                new Jurisdicao("LOCPREV", "ERSP"),
                new Jurisdicao("MAC LAREN", "ERRJ"),
                new Jurisdicao("MAGNUS", "ERMG"),
                new Jurisdicao("MAIS VIDA PREV", "ERSP"),
                new Jurisdicao("MANNESMANN", "ERMG"),
                new Jurisdicao("MAPPIN", "ERSP"),
                new Jurisdicao("MARCOPREV", "ERRS"),
                new Jurisdicao("MARISOL", "ERRS"),
                new Jurisdicao("MAUA PREV", "ERRJ"),
                new Jurisdicao("MBPREV", "ERSP"),
                new Jurisdicao("MCPREV", "ERSP"),
                new Jurisdicao("MENDESPREV", "ERMG"),
                new Jurisdicao("MERCAPREV", "ERSP"),
                new Jurisdicao("MERCERPREV", "ERSP"),
                new Jurisdicao("MESSIUS", "ERSP"),
                new Jurisdicao("METRUS", "ERSP"),
                new Jurisdicao("MM PREV", "ERSP"),
                new Jurisdicao("MM PREVI", "ERSP"),
                new Jurisdicao("MONGERAL", "ERRJ"),
                new Jurisdicao("MSD PREV", "ERSP"),
                new Jurisdicao("MULTIBRA", "ERSP"),
                new Jurisdicao("MULTIBRA INSTITUIDOR", "ERSP"),
                new Jurisdicao("MULTICOOP", "ERSP"),
                new Jurisdicao("MULTIPARANA", "ERRS"),
                new Jurisdicao("MULTIPENSIONS", "ERSP"),
                new Jurisdicao("MULTIPLA", "ERSP"),
                new Jurisdicao("MULTIPREV", "ERSP"),
                new Jurisdicao("MÚTUOPREV", "ERSP"),
                new Jurisdicao("NALCOPREV", "ERSP"),
                new Jurisdicao("NÉOS", "ERMG"),
                new Jurisdicao("NOROESTE", "ERSP"),
                new Jurisdicao("NUCLEOS", "ERRJ"),
                new Jurisdicao("OABPREV-GO", "ERMG"),
                new Jurisdicao("OABPREV-MG", "ERMG"),
                new Jurisdicao("OABPREVNORDESTE", "ERPE"),
                new Jurisdicao("OABPREV-PR", "ERRS"),
                new Jurisdicao("OABPREV-RJ", "ERRJ"),
                new Jurisdicao("OABPREV-RS", "ERRS"),
                new Jurisdicao("OABPREV-SC", "ERRS"),
                new Jurisdicao("OABPREV-SP", "ERSP"),
                new Jurisdicao("OESPREV", "ERSP"),
                new Jurisdicao("ORIUS", "ERSP"),
                new Jurisdicao("P&G PREV", "ERSP"),
                new Jurisdicao("PARSE", "ERRS"),
                new Jurisdicao("PEIXOTO", "ERRJ"),
                new Jurisdicao("PENA BRANCA", "ERSP"),
                new Jurisdicao("PETROS", "ERRJ"),
                new Jurisdicao("PFIZER PREV", "ERSP"),
                new Jurisdicao("PHILIP MORRIS", "ERRS"),
                new Jurisdicao("PINUSPREV", "ERSP"),
                new Jurisdicao("PLANEJAR", "ERSP"),
                new Jurisdicao("PLPREV", "ERSP"),
                new Jurisdicao("PORTOPREV", "ERSP"),
                new Jurisdicao("PORTUS", "ERRJ"),
                new Jurisdicao("POSTALIS", "ERSP"),
                new Jurisdicao("POTIPREV", "ERPE"),
                new Jurisdicao("POUPREV", "ERDF"),
                new Jurisdicao("PREBEG", "ERMG"),
                new Jurisdicao("PRECE", "ERRJ"),
                new Jurisdicao("PREV PEPSICO", "ERSP"),
                new Jurisdicao("PREVBEP", "ERPE"),
                new Jurisdicao("PREVCAPCO", "ERSP"),
                new Jurisdicao("PREVCHEVRON", "ERSP"),
                new Jurisdicao("PREVCOM-BRC", "ERMG"),
                new Jurisdicao("PREVCOM-MG", "ERMG"),
                new Jurisdicao("PREVCOOP", "ERMG"),
                new Jurisdicao("PREVCUMMINS", "ERSP"),
                new Jurisdicao("PREVDATA", "ERRJ"),
                new Jurisdicao("PREVDEUTSCHE", "ERSP"),
                new Jurisdicao("PREVDOW", "ERSP"),
                new Jurisdicao("PREVEME", "ERSP"),
                new Jurisdicao("PREVEME II", "ERSP"),
                new Jurisdicao("PREVER HAAS", "ERSP"),
                new Jurisdicao("PREVEREADY", "ERSP"),
                new Jurisdicao("PREVES", "ERMG"),
                new Jurisdicao("PREVESTIRENO", "ERSP"),
                new Jurisdicao("PREVHAB", "ERRJ"),
                new Jurisdicao("PREVHENKEL", "ERSP"),
                new Jurisdicao("PREVI - FIERN", "ERPE"),
                new Jurisdicao("PREVI CIBA", "ERSP"),
                new Jurisdicao("PREVI GILLETTE", "ERRJ"),
                new Jurisdicao("PREVI INCEPA", "ERRS"),
                new Jurisdicao("PREVI NOVARTIS", "ERSP"),
                new Jurisdicao("PREVI/BB", "ERRJ"),
                new Jurisdicao("PREVI/CIBA", "ERSP"),
                new Jurisdicao("PREVIARMCO", "ERSP"),
                new Jurisdicao("PREVIBAN", "ERPE"),
                new Jurisdicao("PREVI-BANERJ", "ERRJ"),
                new Jurisdicao("PREVIBAYER", "ERSP"),
                new Jurisdicao("PREVIBENTONIT", "ERSP"),
                new Jurisdicao("PREVIBOSCH", "ERSP"),
                new Jurisdicao("PREVICAR", "ERSP"),
                new Jurisdicao("PREVICAT", "ERSP"),
                new Jurisdicao("PREVICEL", "ERRS"),
                new Jurisdicao("PREVI-CLARIANT", "ERSP"),
                new Jurisdicao("PREVICOKE", "ERRJ"),
                new Jurisdicao("PREVIDA", "ERSP"),
                new Jurisdicao("PREVIDÊNCIA USIMINAS", "ERMG"),
                new Jurisdicao("PREVIDEXXONMOBIL", "ERRS"),
                new Jurisdicao("PREVI-ERICSSON", "ERSP"),
                new Jurisdicao("PREVIFF", "ERRJ"),
                new Jurisdicao("PREVIG", "ERRS"),
                new Jurisdicao("PREVI-GM", "ERSP"),
                new Jurisdicao("PREVIHONDA", "ERSP"),
                new Jurisdicao("PREVIK", "ERRS"),
                new Jurisdicao("PREVIKODAK", "ERSP"),
                new Jurisdicao("PREVILAVORO", "ERSP"),
                new Jurisdicao("PREVILEAF", "ERRS"),
                new Jurisdicao("PREVILIQUID", "ERRJ"),
                new Jurisdicao("PREVILLARES", "ERSP"),
                new Jurisdicao("PREVILLOYDS", "ERSP"),
                new Jurisdicao("PREVIM", "ERRJ"),
                new Jurisdicao("PREVIMA", "ERRJ"),
                new Jurisdicao("PREVIMAT", "ERMG"),
                new Jurisdicao("PREVINDUS", "ERRJ"),
                new Jurisdicao("PREVINOR", "ERRJ"),
                new Jurisdicao("PREVINORTE", "ERDF"),
                new Jurisdicao("PREVIP", "ERSP"),
                new Jurisdicao("PREVIPLAN", "ERSP"),
                new Jurisdicao("PREVIQ", "ERSP"),
                new Jurisdicao("PREVIRB", "ERRJ"),
                new Jurisdicao("PREVIREFINACOES", "ERSP"),
                new Jurisdicao("PREVISAO", "ERSP"),
                new Jurisdicao("PREVISC", "ERRS"),
                new Jurisdicao("PREVISCANIA", "ERSP"),
                new Jurisdicao("PREVISERV", "ERRJ"),
                new Jurisdicao("PREVI-SIEMENS", "ERSP"),
                new Jurisdicao("PREVISTIHL", "ERRS"),
                new Jurisdicao("PREVITDB", "ERSP"),
                new Jurisdicao("PREVITINTAS", "ERRJ"),
                new Jurisdicao("PREVI-TOKYO", "ERSP"),
                new Jurisdicao("PREVIVER", "ERPE"),
                new Jurisdicao("PREVMILL", "ERSP"),
                new Jurisdicao("PREVMOBIL", "ERSP"),
                new Jurisdicao("PREVMON", "ERSP"),
                new Jurisdicao("PREVMUTUA", "ERDF"),
                new Jurisdicao("PREVNORDESTE", "ERMG"),
                new Jurisdicao("PREVPISA", "ERRS"),
                new Jurisdicao("PREV-PR", "ERRS"),
                new Jurisdicao("PREVSAN", "ERMG"),
                new Jurisdicao("PREVSOMPO", "ERSP"),
                new Jurisdicao("PREVTOKIO", "ERSP"),
                new Jurisdicao("PREVUNIAO", "ERRJ"),
                new Jurisdicao("PREVUNISUL", "ERRS"),
                new Jurisdicao("PRHOSPER", "ERSP"),
                new Jurisdicao("PRODUBAN", "ERPE"),
                new Jurisdicao("PRO-FUTURO", "ERSP"),
                new Jurisdicao("PROMON", "ERSP"),
                new Jurisdicao("PSS", "ERSP"),
                new Jurisdicao("QUANTA", "ERRS"),
                new Jurisdicao("RAIZPREV", "ERSP"),
                new Jurisdicao("RANDONPREV", "ERRS"),
                new Jurisdicao("RBS PREV", "ERRS"),
                new Jurisdicao("REAL GRANDEZA", "ERRJ"),
                new Jurisdicao("RECKITTPREV", "ERSP"),
                new Jurisdicao("REFER", "ERRJ"),
                new Jurisdicao("REGIUS", "ERDF"),
                new Jurisdicao("RENOPREV", "ERRS"),
                new Jurisdicao("RESAPREV", "ERSP"),
                new Jurisdicao("RIBEIRAO PREV", "ERSP"),
                new Jurisdicao("RIGEPREV", "ERSP"),
                new Jurisdicao("RJPREV", "ERRJ"),
                new Jurisdicao("ROCHEPREV", "ERSP"),
                new Jurisdicao("RS-PREV", "ERRS"),
                new Jurisdicao("RUMOS", "ERSP"),
                new Jurisdicao("SABESPREV", "ERSP"),
                new Jurisdicao("SANEPREVI", "ERMG"),
                new Jurisdicao("SANPREV", "ERSP"),
                new Jurisdicao("SANTANDER BANES", "ERSP"),
                new Jurisdicao("SANTANDERPREVI", "ERSP"),
                new Jurisdicao("SAO BERNARDO", "ERSP"),
                new Jurisdicao("SAO FRANCISCO", "ERDF"),
                new Jurisdicao("SAO RAFAEL", "ERRJ"),
                new Jurisdicao("SARAHPREV", "ERDF"),
                new Jurisdicao("SBOTPREV", "ERSP"),
                new Jurisdicao("SBPREV", "ERDF"),
                new Jurisdicao("SCHNEIDER", "ERSP"),
                new Jurisdicao("SCPREV", "ERRS"),
                new Jurisdicao("SEAGRAM", "ERSP"),
                new Jurisdicao("SEBRAE PREVIDENCIA", "ERDF"),
                new Jurisdicao("SEGURIDADE", "ERMG"),
                new Jurisdicao("SERGUS", "ERPE"),
                new Jurisdicao("SERPROS", "ERRJ"),
                new Jurisdicao("SIAS", "ERRJ"),
                new Jurisdicao("SICOOB PREVI", "ERDF"),
                new Jurisdicao("SILIUS", "ERRS"),
                new Jurisdicao("SINDPD", "ERSP"),
                new Jurisdicao("SINGER", "ERSP"),
                new Jurisdicao("SISTEL", "ERDF"),
                new Jurisdicao("SITRATUH PREVIDÊNCIA", "ERRS"),
                new Jurisdicao("SOCEPMI", "ERDF"),
                new Jurisdicao("SOMUPP", "ERSP"),
                new Jurisdicao("SP-PREVCOM", "ERSP"),
                new Jurisdicao("STEIO", "ERRJ"),
                new Jurisdicao("SUL PREVIDÊNCIA", "ERRS"),
                new Jurisdicao("SULAMULTI", "ERSP"),
                new Jurisdicao("SULFABRILPREV", "ERSP"),
                new Jurisdicao("SUPRE", "ERRS"),
                new Jurisdicao("SUPREV", "ERSP"),
                new Jurisdicao("SWPREV", "ERSP"),
                new Jurisdicao("SYNGENTA PREVI", "ERSP"),
                new Jurisdicao("TECHNOS", "ERDF"),
                new Jurisdicao("TELOS", "ERRJ"),
                new Jurisdicao("TETRA PAK PREV", "ERSP"),
                new Jurisdicao("TEXPREV", "ERRJ"),
                new Jurisdicao("TEXTIL PREV", "ERSP"),
                new Jurisdicao("TOYOTA PREVI", "ERSP"),
                new Jurisdicao("TRAMONTINAPREV", "ERRS"),
                new Jurisdicao("TRICHESPREV", "ERRS"),
                new Jurisdicao("UASPREV", "ERSP"),
                new Jurisdicao("UBB-PREV", "ERSP"),
                new Jurisdicao("ULTRAPREV", "ERSP"),
                new Jurisdicao("UNILEVERPREV", "ERSP"),
                new Jurisdicao("UNIPREVI", "ERMG"),
                new Jurisdicao("UNISYS-PREVI", "ERRJ"),
                new Jurisdicao("URANUS", "ERRJ"),
                new Jurisdicao("UTCPREV", "ERRS"),
                new Jurisdicao("VALIA", "ERRJ"),
                new Jurisdicao("VALUE PREV", "ERSP"),
                new Jurisdicao("VAN LEER", "ERSP"),
                new Jurisdicao("VBPP", "ERSP"),
                new Jurisdicao("VEXTY", "ERSP"),
                new Jurisdicao("VIKINGPREV", "ERRS"),
                new Jurisdicao("VISÃO PREV", "ERSP"),
                new Jurisdicao("VIVA", "ERDF"),
                new Jurisdicao("VOITH PREV", "ERSP"),
                new Jurisdicao("VULCAPREV", "ERRJ"),
                new Jurisdicao("VWPP", "ERSP"),
                new Jurisdicao("WEG", "ERRS"),
                new Jurisdicao("WYETH PREV", "ERSP")
            };
    
            StringBuilder sqlBuilder = new StringBuilder();
            String baseInsert = "INSERT INTO %s.jurisdicoes (id_jurisdicao, id_entidade, id_escritorio) ";
            String selectTemplate = " SELECT %d, a.id_entidade, b.id_escritorio FROM %s.entidades a, %s.escritorios b WHERE b.abreviatura = '%s' AND a.sigla = '%s' AND NOT EXISTS (SELECT 1 FROM %s.jurisdicoes c WHERE c.id_entidade = a.id_entidade AND c.id_escritorio = b.id_escritorio)";
    
            sqlBuilder.append(String.format(baseInsert, schema));
    
            for (int i = 0; i < jurisdicoes.length; i++) {
                Jurisdicao j = jurisdicoes[i];
                sqlBuilder.append(String.format(selectTemplate, i+1, 
                    schema, schema, j.abreviaturaEscritorio, j.siglaEntidade, schema));
                
                if (i < jurisdicoes.length - 1) {
                    sqlBuilder.append(" UNION ");
                }
            }
    
            return sqlBuilder.toString();
        }
}
