package com.virtus.database.scripts;

public class UsersScripts {
        public static String insertUsersIfNotExists(String schema) {
                class User {
                        String username;
                        String password;
                        String email;
                        String mobile;
                        String name;
                        int idRole;

                        User(String username, String password, String email, String mobile, String name, int idRole) {
                                this.username = username;
                                this.password = password;
                                this.email = email;
                                this.mobile = mobile;
                                this.name = name;
                                this.idRole = idRole;
                        }
                }

                User[] users = new User[] {
                                new User("alessandro.vaine",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "alessandro.vaine@previc.gov.br", "", "ALESSANDRO VAINE", 4),
                                new User("alexandre", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "", "",
                                                "ALEXANDRE BISPO NUNES GRECO", 4),
                                new User("alfredo", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "ALFREDO SULZBACHER WONDRACEK", 4),
                                new User("alvaro", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "ALVARO RODRIGUES DOS SANTOS NETO", 4),
                                new User("andre.goncalves",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "andre.goncalves@previc.gov.br", "", "ANDRE MACHADO GONÇALVES", 4),
                                new User("andre.silva", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "", "",
                                                "ANDRE LUIS SOUZA DA SILVA", 4),
                                new User("angelica.campinho",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "angelica.campinho@previc.gov.br", "",
                                                "ANGELICA DE ALMEIDA FONSECA CAMPINHO", 4),
                                new User("annette.pinto",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "annette.pinto@previc.gov.br", "", "ANNETTE LOPES PINTO", 4),
                                new User("antonio.frainer",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "", "",
                                                "ANTONIO SEVERO FRAINER", 4),
                                new User("antonio.garcia",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "", "",
                                                "ANTONIO AUGUSTO GARCIA", 4),
                                new User("antonio.portes",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "", "",
                                                "ANTONIO ALBERTO GROSSI PORTES", 4),
                                new User("aria", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "aria@gmail.com",
                                                "61 984385415", "Ária Ohashi", 1),
                                new User("arnaldo", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "arnaldo@gmail.com",
                                                "61 984385415", "Arnaldo Burle", 1),
                                new User("carlos", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "CARLOS MARNE DIAS ALVES", 4),
                                new User("carlos.buccos",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "carlos.buccos@previc.gov.br", "", "CARLOS EDUARDO BUCCOS SILVEIRA", 4),
                                new User("carlos.neves", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "", "",
                                                "CARLOS EUGÊNIO D'AVILA NEVES", 4),
                                new User("charles.dantas",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "charles.dantas@previc.gov.br", "", "CHARLES SILVA DANTAS", 4),
                                new User("charles.diniz",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "charles.diniz@previc.gov.br", "", "CHARLES DINIZ BOTELHO DA SILVA", 4),
                                new User("chow", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "", "",
                                                "CHOW CHI KWAN", 4),
                                new User("clovis.coelho",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "clovis.coelho@previc.gov.br", "", "CLOVIS GUIMARAES COELHO", 4),
                                new User("dagomar", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "DAGOMAR ALECIO ANHE", 4),
                                new User("dauto", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "DAUTO BARBOSA DE SOUSA", 4),
                                new User("david.coutinho",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "david.coutinho@previc.gov.br", "", "DAVID PRATES COUTINHO", 4),
                                new User("delma", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "DELMA PIRES GALVÃO", 4),
                                new User("diogo.araujo", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "diogo.araujo@previc.gov.br", "", "DIOGO BORBA DE ARAUJO", 4),
                                new User("douglas", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "DOUGLAS CARVALHO DUARTE", 4),
                                new User("eduardo.meireles",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "eduardo.meireles@previc.gov.br", "", "EDUARDO MENEZES MEIRELES", 4),
                                new User("elianeoliveira.costa",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "elianeoliveira.costa@previc.gov.br", "", "ELIANE OLIVEIRA DA COSTA",
                                                4),
                                new User("elyson", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "ELYSON MARCEL TOME SCAFATI", 4),
                                new User("enaide", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "ENAIDE MARIA TEIXEIRA DE SOUZA", 4),
                                new User("estevam.brayn",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "estevam.brayn@previc.gov.br", "", "ESTEVAM BRAYN", 4),
                                new User("evelyn", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "EVELYN DE QUEIROZ ITO", 4),
                                new User("felipe", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "FELIPE SPOLAVORI MARTINS", 4),
                                new User("francisco.arruda",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "francisco.arruda@previc.gov.br", "", "FRANCISCO HELIO ARRUDA COELHO",
                                                4),
                                new User("francisco.junior",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "", "",
                                                "FRANCISCO RODRIGUES BRAGA JÚNIOR", 4),
                                new User("germano.barreira",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "germano.barreira@previc.gov.br", "", "GERMANO CAVALCANTI BARREIRA", 4),
                                new User("giselle", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "GISELLE LOPES MIRANDA", 4),
                                new User("hamilton", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "HAMILTON NOLETO MOREIRA", 4),
                                new User("helvio", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "HELVIO ANTONIO PEREIRA MARINHO", 4),
                                new User("hilton", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "HILTON DE ENZO MITSUNAGA", 4),
                                new User("humberto", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "HUMBERTO DA SILVA JUNIOR", 4),
                                new User("isabel.cmaia", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "isabel.cmaia@previc.gov.br", "", "ISABEL CRISTINA MAIA", 4),
                                new User("izabel", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "IZABEL CRISTINA REZENDE NEVES", 4),
                                new User("james", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "james@gmail.com",
                                                "61 984385415", "James Taylor", 4),
                                new User("jorge", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "JORGE LUIZ FONSECA FRISCHEISEN", 4),
                                new User("jose.cestari", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "jose.cestari@previc.gov.br", "", "JOSE MARCOS CARVALHO CESTARI", 4),
                                new User("jose.chedeak", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "", "",
                                                "JOSÉ CARLOS SAMPAIO CHEDEAK", 4),
                                new User("jose.fernandes",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "", "",
                                                "JOSÉ RICARDO FERREIRA FERNANDES", 4),
                                new User("jose.pires", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "", "",
                                                "JOSE ERALDO PIRES", 4),
                                new User("jucinea", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "JUCINEA DAS MERCES NASCIMENTO", 4),
                                new User("juliana.pereira",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "juliana.pereira@previc.gov.br", "", "JULIANA HELENA DE PAIVA PEREIRA",
                                                4),
                                new User("leonardo", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "leofiuza@gmail.com", "61 984385415", "Leonardo Fiuza", 4),
                                new User("leonardo.alves",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "leonardo.alves@previc.gov.br", "", "LEONARDO FROTA ALVES", 4),
                                new User("luciano.draghetti",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "luciano.draghetti@previc.gov.br", "", "LUCIANO DRAGHETTI", 4),
                                new User("luciano.pinheiro",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "", "",
                                                "LUCIANO VILELA PINHEIRO", 4),
                                new User("luis.angoti", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "", "",
                                                "LUÍS RONALDO MARTINS ANGOTI", 4),
                                new User("luis.barbosa", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "", "",
                                                "LUIS GUSTAVO DA CUNHA BARBOSA", 4),
                                new User("luis.pugliese",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "", "",
                                                "LUIS ANTONIO ALVES PUGLIESE", 4),
                                new User("luiz", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "", "",
                                                "LUIZ ALBERTO GONÇALVES FIALHO", 4),
                                new User("maique", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "MAIQUE PEREIERA AGNES", 4),
                                new User("marcelo.melo", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "", "",
                                                "MARCELO FREITAS TOLEDO DE MELO", 4),
                                new User("marcelo.wajsenzon",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "marcelo.wajsenzon@previc.gov.br", "", "MARCELO ZELIK WAJSENZON", 4),
                                new User("marcia.vivas", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "marcia.vivas@previc.gov.br", "", "MÁRCIA VIVAS DE ARAÚJO", 4),
                                new User("marcio", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "MARCIO MATHEUS GUIMARAES MACHADO", 4),
                                new User("marcus", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "MARCUS VINÍCIUS PINTO DE SOUZA", 4),
                                new User("maria", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "MARIA BATISTA DA SILVA", 4),
                                new User("maria.cherulli",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "maria.cherulli@previc.gov.br", "", "MARIA JULIETA CHERULLI MACHADO",
                                                4),
                                new User("maria.fpimenta",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "maria.fpimenta@previc.gov.br", "", "MARIA DA GLÓRIA FERREIRA PIMENTA",
                                                4),
                                new User("marina", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "MARINA MARCONDES DA SILVA ALVES", 4),
                                new User("masaru", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "masaru@gmail.com",
                                                "61 984385415", "Masaru Ohashi Jr", 6),
                                new User("mauricio.lundgren",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "mauricio.lundgren@previc.gov.br", "", "MAURICIO TIGRE VALOIS LUNDGREN",
                                                4),
                                new User("mauricio.nakata",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "mauricio.nakata@previc.gov.br", "", "MAURICIO DE AGUIRRE NAKATA", 4),
                                new User("maury.oliveira",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "maury.oliveira@previc.gov.br", "", "MAURY COELHO DE OLIVEIRA", 4),
                                new User("nercilia", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "NERCILIA BARROS DE SOUZA", 4),
                                new User("nivea", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "NIVEA CLEIDE FERREIRA DOS SANTOS", 4),
                                new User("otavio.reis", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "otavio.reis@previc.gov.br", "", "OTAVIO LIMA REIS", 4),
                                new User("patricia", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "PATRICIA CERQUEIRA MONTEIRO", 4),
                                new User("paulo.diniz", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "", "",
                                                "PAULO NOBILE DINIZ", 4),
                                new User("paulo.matsumoto",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "paulo.matsumoto@previc.gov.br", "", "PAULO ANDRÉ HIDEAKI MATSUMOTO",
                                                4),
                                new User("paulo.vitorino",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "", "",
                                                "PAULO VITORINO SILVA DE SOUSA", 4),
                                new User("pedro", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "PEDRO IWAO KAKITANI", 4),
                                new User("pedro.pauloeugenio",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "pedro.pauloeugenio@previc.gov.br", "", "PEDRO PAULO EUGENIO", 4),
                                new User("peterson.goncalves",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "peterson.goncalves@previc.gov.br", "", "PETERSON GONCALVES", 4),
                                new User("rafael", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "RAFAEL MAGALHÃES", 4),
                                new User("raquel.gerhardt",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "raquel.gerhardt@previc.gov.br", "", "RAQUEL GERHARDT", 4),
                                new User("rita", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "", "",
                                                "RITA DE CASSIA CORREA DA SILVA", 4),
                                new User("roberto.sakamoto",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "roberto.sakamoto@previc.gov.br", "", "ROBERTO SAKAMOTO", 4),
                                new User("rodrigo.abreu",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "rodrigo.abreu@previc.gov.br", "", "RODRIGO MARTINS ABREU", 4),
                                new User("rodrigo.andrade",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "rodrigo.andrade@previc.gov.br", "", "RODRIGO RANGEL DE ANDRADE", 4),
                                new User("rodrigo.oliveira",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "rodrigo.oliveira@previc.gov.br", "", "RODRIGO AIRES DE OLIVEIRA", 4),
                                new User("romulo", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "ROMULO GONÇALVES DA SILVA", 4),
                                new User("sergio", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "SERGIO DJUNDI TANIGUCHI", 4),
                                new User("simone", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "SIMONE CORRÊA REIS", 4),
                                new User("vandeisa", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "VANDEISA MOURA ALMEIDA", 4),
                                new User("vanessa", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "VANESSA DA ROCHA VIER", 4),
                                new User("veronica", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "VERONICA SOUSA SILVEIRA", 4),
                                new User("vitor", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "VITOR FERNANDES RIBEIRO DE OLIVEIRA", 4),
                                new User("walter", "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "",
                                                "",
                                                "WALTER DE CARVALHO PARENTE", 4),
                                new User("wander.mingardi",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "wander.mingardi@previc.gov.br", "", "WANDER RICARDO MINGARDI", 4),
                                new User("wania.capparelli",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6",
                                                "wania.capparelli@previc.gov.br", "", "WÂNIA MARIA FRANÇA CAPPARELLI",
                                                4),
                                new User("wellington.marques",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "", "",
                                                "WELINGTON RODRIGUES MARQUES", 4),
                                new User("wellington.pereira",
                                                "$2a$10$4Q6xe3fxi1HC8PX7LSGIkeYpkNa9OdpUv3rUD0ht4g3Fu6gJgg1g6", "", "",
                                                "WELLINGTON MARCOS ASSIS PEREIRA", 4)
                };

                StringBuilder sb = new StringBuilder();
                int id = 1;

                for (User user : users) {
                        sb.append(String.format(
                                        "IF NOT EXISTS (SELECT 1 FROM %s.users WHERE username = '%s')\n" +
                                                        "BEGIN\n" +
                                                        "    INSERT INTO %s.users (id_user, username, password, email, mobile, name, id_role, id_author, criado_em)\n"
                                                        +
                                                        "    VALUES ((SELECT MAX(id_user)+1 FROM %s.users), '%s', '%s', '%s', '%s', '%s', %d, 1, GETDATE());\n"
                                                        +
                                                        "END;\n\n",
                                        schema, user.username.replace("'", "''"),
                                        schema, schema,
                                        user.username.replace("'", "''"),
                                        user.password.replace("'", "''"),
                                        user.email.replace("'", "''"),
                                        user.mobile.replace("'", "''"),
                                        user.name.replace("'", "`"),
                                        user.idRole));
                }

                return sb.toString();
        }

}
